### ISSUE TITLE
Cancel CI runs if PRs get updated

### ISSUE THREAD

**Issue by k-sareen** [mmtk/mmtk-core#728]
We should add the following to every CI in order to cancel a run for a PR if a new commit occurs. Better if we don't waste compute cycles for nothing.

```yaml
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```
